[package]
name = "dose-types"
version = "0.1.0"
authors = ["Adam <sector-f@users.noreply.github.com>"]

[dependencies]
serde = "1.0.14"
serde_derive = "1.0.14"

[dev-dependencies]
serde_json = "1.0.3"
