[package]
name = "dose"
version = "0.1.0"
authors = ["Adam <sector-f@users.noreply.github.com>"]

[dependencies]
serde = "1.0.14"
serde_derive = "1.0.14"
serde_json = "1.0.3"
reqwest = "0.6.2"
daemonize = "0.2.3"
libc = "0.2.30"
url = "1.5.1"
dose-types = { path = "../dose-types" }
