[package]
name = "dose-client"
version = "0.1.0"
authors = ["Adam <sector-f@users.noreply.github.com>"]

[dependencies]
clap = "2.31.2"
serde = "1.0.38"
serde_json = "1.0.14"

dose-types = { path = "../dose-types" }
